In [2]:
#!pip install pennylane --upgrade
#!pip install pennylane-sf pennylane-qiskit pennylane-cirq pennylane-forest pennylane-qsharp
#!pip install autograd tensorflow>=1.13.2

In [3]:
%matplotlib inline
import pennylane as qml
from pennylane import numpy as np

In [4]:
dev = qml.device("default.qubit", wires=2)

In [6]:
@qml.qnode(dev)
def state_prep(x):
    # Encode input x into quantum state
    qml.QubitStateVector(x,wires=[0,1])

    return qml.probs(wires=[0, 1])

In [10]:
X=np.random.randn(4)
X=X/np.linalg.norm(X)

print(X**2)
state_prep(X)

[0.63652771 0.03518455 0.07600368 0.25228406]


array([0.63652771, 0.03518455, 0.07600368, 0.25228406])

In [65]:
'''
@qml.qnode(dev)
def my_quantum_function():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.probs(wires=[0, 1])
'''
A=np.random.rand(4,4)
U,S,V=np.linalg.svd(A)
print(np.round(U**2,3))

@qml.qnode(dev)
def my_quantum_function():
    qml.PauliX(wires=[0])
    qml.QubitUnitary(U,wires=[0,1])
    return qml.probs(wires=[0, 1])

[[0.122 0.009 0.056 0.813]
 [0.359 0.097 0.544 0.   ]
 [0.176 0.761 0.001 0.062]
 [0.343 0.132 0.399 0.125]]


In [66]:
print(my_quantum_function())

[0.05595081 0.5443804  0.00068078 0.39898801]
